name: Run Messenger Bot

on:
  push:
  workflow_dispatch:

jobs:
  bot:
    runs-on: ubuntu-latest

    steps:
      # Repo clone
      - name: Checkout Code
        uses: actions/checkout@v3

      # Node setup
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install packages
      - name: Install Dependencies
        run: npm install

      # Start Bot
      - name: Start Bot
        run: |
          echo "Starting Bot..."
          node index.js
          sleep 999999
